In [3]:
#!pip install pandas

In [18]:
data = {
    'Empid': [101,102,103,104,105,106,107,108,109,110],
    'Empname': ['Ram','Shyam','Mohan' , 'Rohan','Anu','Riya','Simran','Nameera' ,'Mohit','Bhavna '],
    'Empsalary':[42121,43232,21331,43532,83637,37212,18173,73536,21341,42313]
}

In [7]:
#•	Pandas is used to Extract and  Transform  the data 
#•	Loading data from a source like csv , xls, parqueet  , json and database etc
#•	Data should be series(1 D)  or DataFrame(Tabular Format)

In [15]:
import pandas as pd
import numpy as np

In [16]:
print(data)

{'Empid': [101, 102, 103, 104, 105, 106, 107, 108, 109], 'Empname': ['Ram', 'Shyam', 'Mohan', 'Rohan', 'Anu', 'Riya', 'Simran', 'Nameera', 'Mohit', 'Bhavna '], 'Empsalary': [42121, 43232, 21331, 43532, 83637, 37212, 18173, 73536, 21341, 42313]}

In [19]:
df = pd.DataFrame(data)

In [20]:
df

   Empid  Empname  Empsalary
0    101      Ram      42121
1    102    Shyam      43232
2    103    Mohan      21331
3    104    Rohan      43532
4    105      Anu      83637
5    106     Riya      37212
6    107   Simran      18173
7    108  Nameera      73536
8    109    Mohit      21341
9    110  Bhavna       42313

In [21]:
df.head()

   Empid Empname  Empsalary
0    101     Ram      42121
1    102   Shyam      43232
2    103   Mohan      21331
3    104   Rohan      43532
4    105     Anu      83637

In [23]:
df.head(2)

   Empid Empname  Empsalary
0    101     Ram      42121
1    102   Shyam      43232

In [24]:
df.tail()

   Empid  Empname  Empsalary
5    106     Riya      37212
6    107   Simran      18173
7    108  Nameera      73536
8    109    Mohit      21341
9    110  Bhavna       42313

In [25]:
df.tail(2)

   Empid  Empname  Empsalary
8    109    Mohit      21341
9    110  Bhavna       42313

In [26]:
df.Empname

0        Ram
1      Shyam
2      Mohan
3      Rohan
4        Anu
5       Riya
6     Simran
7    Nameera
8      Mohit
9    Bhavna
Name: Empname, dtype: str

In [29]:
df.Empsalary

0    42121
1    43232
2    21331
3    43532
4    83637
5    37212
6    18173
7    73536
8    21341
9    42313
Name: Empsalary, dtype: int64

In [30]:
df.Empsalary.sum()

np.int64(426428)

In [31]:
df.Empsalary.max()

np.int64(83637)

In [32]:
df.Empsalary.min()

np.int64(18173)

In [33]:
df.Empsalary.mean()

np.float64(42642.8)

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    10 non-null     str
 2   Empsalary  10 non-null     int64
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

In [35]:
df.describe()

           Empid     Empsalary
count   10.00000     10.000000
mean   105.50000  42642.800000
std      3.02765  21532.036389
min    101.00000  18173.000000
25%    103.25000  25308.750000
50%    105.50000  42217.000000
75%    107.75000  43457.000000
max    110.00000  83637.000000

In [50]:
data = {
    'Empid': [101,102,103,104,105,106,107,108,109,110],
    'Empname': ['Ram','Shyam','Mohan' , np.nan,'Anu','Riya','Simran','Nameera' ,'Mohit','Bhavna '],
    'Empsalary':[42121,43232,np.nan,43532,83637,37212,np.nan,73536,21341,42313]
}

In [51]:
df = pd.DataFrame(data)

In [52]:
df

   Empid  Empname  Empsalary
0    101      Ram    42121.0
1    102    Shyam    43232.0
2    103    Mohan        NaN
3    104      NaN    43532.0
4    105      Anu    83637.0
5    106     Riya    37212.0
6    107   Simran        NaN
7    108  Nameera    73536.0
8    109    Mohit    21341.0
9    110  Bhavna     42313.0

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    9 non-null      str
 2   Empsalary  8 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 372.0 bytes

In [55]:
df.isnull()

   Empid  Empname  Empsalary
0  False    False      False
1  False    False      False
2  False    False       True
3  False     True      False
4  False    False      False
5  False    False      False
6  False    False       True
7  False    False      False
8  False    False      False
9  False    False      False

In [56]:
df.isnull().sum()

Empid        0
Empname      1
Empsalary    2
dtype: int64

In [58]:
df.isnull().sum().sum()

np.int64(3)

In [59]:
df.dropna()

   Empid  Empname  Empsalary
0    101      Ram    42121.0
1    102    Shyam    43232.0
4    105      Anu    83637.0
5    106     Riya    37212.0
7    108  Nameera    73536.0
8    109    Mohit    21341.0
9    110  Bhavna     42313.0

In [60]:
df

   Empid  Empname  Empsalary
0    101      Ram    42121.0
1    102    Shyam    43232.0
2    103    Mohan        NaN
3    104      NaN    43532.0
4    105      Anu    83637.0
5    106     Riya    37212.0
6    107   Simran        NaN
7    108  Nameera    73536.0
8    109    Mohit    21341.0
9    110  Bhavna     42313.0

In [61]:
#replace
df.fillna("Not Found!")

   Empid     Empname   Empsalary
0    101         Ram     42121.0
1    102       Shyam     43232.0
2    103       Mohan  Not Found!
3    104  Not Found!     43532.0
4    105         Anu     83637.0
5    106        Riya     37212.0
6    107      Simran  Not Found!
7    108     Nameera     73536.0
8    109       Mohit     21341.0
9    110     Bhavna      42313.0

In [63]:
#It works because it does not reflect on original data if you want you can do df = df.fillna("Not Found!")
df.Empsalary.sum()

np.float64(386924.0)

In [65]:
df.Empsalary.fillna('No data')

0    42121.0
1    43232.0
2    No data
3    43532.0
4    83637.0
5    37212.0
6    No data
7    73536.0
8    21341.0
9    42313.0
Name: Empsalary, dtype: object

In [66]:
df.Empsalary.fillna(12000)

0    42121.0
1    43232.0
2    12000.0
3    43532.0
4    83637.0
5    37212.0
6    12000.0
7    73536.0
8    21341.0
9    42313.0
Name: Empsalary, dtype: float64

In [67]:
df.Empsalary.fillna(df.Empsalary.mean())

0    42121.0
1    43232.0
2    48365.5
3    43532.0
4    83637.0
5    37212.0
6    48365.5
7    73536.0
8    21341.0
9    42313.0
Name: Empsalary, dtype: float64

In [90]:
newdf = df.copy()

In [91]:
newdf.Empsalary = newdf.Empsalary.fillna(round(newdf.Empsalary.mean(),2))

In [92]:
newdf

   Empid  Empname  Empsalary
0    101      Ram    42121.0
1    102    Shyam    43232.0
2    103    Mohan    48365.5
3    104      NaN    43532.0
4    105      Anu    83637.0
5    106     Riya    37212.0
6    107   Simran    48365.5
7    108  Nameera    73536.0
8    109    Mohit    21341.0
9    110  Bhavna     42313.0

In [93]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    9 non-null      str
 2   Empsalary  10 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 372.0 bytes

In [85]:
newdf.Empname = newdf.Empname.fillna('No Name')

In [95]:
newdf

   Empid  Empname  Empsalary
0    101      Ram    42121.0
1    102    Shyam    43232.0
2    103    Mohan    48365.5
3    104      NaN    43532.0
4    105      Anu    83637.0
5    106     Riya    37212.0
6    107   Simran    48365.5
7    108  Nameera    73536.0
8    109    Mohit    21341.0
9    110  Bhavna     42313.0

In [94]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    9 non-null      str
 2   Empsalary  10 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 372.0 bytes