In [2]:
!pip install openpyxl

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [10]:
df.shape

(700, 16)

In [11]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [13]:
df.isnull().sum().sum()

np.int64(111)

In [14]:
111/7

15.857142857142858

In [16]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='str')

In [45]:
for col in df.columns:
    if df[col].isnull().sum()>1:
        print(col , '\t',df[col].dtype)

Segment 	 str
Country 	 str
Product 	 str
Discount Band 	 str
Units Sold 	 float64
Sale Price 	 float64
Gross Sales 	 float64
Discounts 	 float64

In [27]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              5
Manufacturing Price     0
Sale Price              7
Gross Sales             5
Discounts               5
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [31]:
df['Discount Band'].unique()

<StringArray>
[nan, 'Low', 'Medium', 'High']
Length: 4, dtype: str

In [33]:
df.Segment.unique()

<StringArray>
[      'Government',        'Midmarket', 'Channel Partners',
       'Enterprise',   'Small Business',                nan]
Length: 6, dtype: str

In [39]:
df.Segment.value_counts()

Segment
Government          294
Midmarket           100
Enterprise          100
Small Business      100
Channel Partners     98
Name: count, dtype: int64

In [40]:
df.Segment.mode()

0    Government
Name: Segment, dtype: str

In [51]:
df.select_dtypes(include=str).columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Month Name'], dtype='str')

In [66]:
for col in df.select_dtypes(include=str).columns:
    print(col ,'\t', df[col].isnull().sum(), '\tMissing Value Replaced By:  '  , df[col].mode()[0])
    df[col] = df[col].fillna(df[col].mode()[0])

Segment 	 8 	Missing Value Replaced By:   Government
Country 	 11 	Missing Value Replaced By:   France
Product 	 8 	Missing Value Replaced By:   Paseo
Discount Band 	 62 	Missing Value Replaced By:   High
Month Name 	 0 	Missing Value Replaced By:   October

In [65]:
# it shows mode values comes on index 0
df.Segment.mode() #it show index
df.Segment.mode()[0] #it shows value on index 0

'Government'

In [74]:
df.select_dtypes(include = int)

,Units Sold,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit
0,1618.5,20.0,32370.0,0.00,32370.00,16185.0,16185.00
1,1321.0,20.0,26420.0,0.00,26420.00,13210.0,13210.00
2,2178.0,15.0,32670.0,0.00,32670.00,21780.0,10890.00
3,888.0,15.0,13320.0,0.00,13320.00,8880.0,4440.00
4,2470.0,15.0,37050.0,0.00,37050.00,24700.0,12350.00
...,...,...,...,...,...,...,...
695,2475.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00
696,546.0,300.0,163800.0,24570.00,139230.00,136500.0,2730.00
697,1368.0,7.0,9576.0,1436.40,8139.60,6840.0,1299.60
698,723.0,7.0,5061.0,759.15,4301.85,3615.0,686.85
699,1806.0,12.0,21672.0,3250.80,18421.20,5418.0,13003.20

In [321]:
for col in df.select_dtypes(include = float).columns:
    if df[col].isnull().sum()>0:
        print(col  ,'\t',  df[col].isnull().sum() ,'\tMissing Value Replaced By:  ', df[col].mean().round(2))
        df[col] = df[col].fillna(round(df[col].mean(),2))

Units Sold 	 5 	Missing Value Replaced By:   1607.88
Sale Price 	 7 	Missing Value Replaced By:   117.91
Gross Sales 	 5 	Missing Value Replaced By:   183967.04
Discounts 	 5 	Missing Value Replaced By:   13077.16

In [138]:

df.Discounts.mode()[0]

np.float64(0.0)

In [148]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [323]:
df = pd.read_excel(r"C:\Users\DELL\Downloads\Financial_Sample.xlsx")

In [324]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              5
Manufacturing Price     0
Sale Price              7
Gross Sales             5
Discounts               5
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [327]:
for col in df.columns:
    if df[col].isnull().sum()>0:
        if df[col].dtype=='str':
            print(col, '\t' , df[col].dtype, '\t\t' , df[col].isnull().sum() , '\tReplaced By : ' , df[col].mode()[0])
            df[col] =  df[col].fillna(df[col].mode()[0])
        else:
            print(col, '\t' , df[col].dtype,'\t', df[col].isnull().sum(), '\tReplaced By : ',round(df[col].mean(),2))
            df[col] = df[col].fillna(round(df[col].mean(),2))

Segment 	 str 		 8 	Replaced By :  Government
Country 	 str 		 11 	Replaced By :  France
Product 	 str 		 8 	Replaced By :  Paseo
Discount Band 	 str 		 62 	Replaced By :  High
Units Sold 	 float64 	 5 	Replaced By :  1607.88
Sale Price 	 float64 	 7 	Replaced By :  117.91
Gross Sales 	 float64 	 5 	Replaced By :  183967.04
Discounts 	 float64 	 5 	Replaced By :  13077.16

In [329]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [335]:
df['Country'].map(lambda val :'USA' if val =='United States of America' else val[0:3].upper())

0      CAN
1      GER
2      FRA
3      GER
4      MEX
      ...
695    FRA
696    MEX
697    MEX
698    CAN
699    USA
Name: Country, Length: 700, dtype: str

In [336]:
df['Country'] = df['Country'].map(lambda val :'USA' if val =='United States of America' else val[0:3].upper())

In [339]:
df['Country']

0      CAN
1      GER
2      FRA
3      GER
4      MEX
      ...
695    FRA
696    MEX
697    MEX
698    CAN
699    USA
Name: Country, Length: 700, dtype: str

In [340]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,CAN,Carretera,High,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,GER,Carretera,High,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [ ]:
df = df.drop(columns=['Month Number' , 'Month Name' , 'Year' ])

In [347]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date
0,Government,CAN,Carretera,High,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01
1,Government,GER,Carretera,High,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01

In [351]:
df.to_csv("Cleaned_Data_0003_Practical.csv" , index =False)