In [1]:
#                                                 🟢 Beginner (20 Questions)
# Show first 10 rows.
# Show last 7 rows.
# Dataset shape.
# Number of rows.
# Number of columns.
# Display all column names.
# Display datatypes.
# Display statistical summary.
# Display only Name column.
# Display Name and Salary.
# Find average salary.
# Find highest salary.
# Find lowest salary.
# Find total salary.
# Count missing values.
# Total missing values.
# Replace missing Name.
# Fill Salary with mean.
# Fill Age with mean.
# Fill Experience with mean.

In [2]:
import pandas as pd
import numpy as np

data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],
    "Name":["Ram","Shyam","Mohan","Rohan","Anu","Riya","Simran","Neha","Mohit","Bhavna",
            "Karan","Amit",np.nan,"Sneha","Pooja","Vikas","Nitin","Asha","Rahul","Priya"],

    "Department":["IT","HR","IT","Sales","Finance","HR","IT","Finance","Sales","IT",
                  "HR","Finance","IT","Sales","HR","IT","Finance","HR","Sales","IT"],

    "City":["Delhi","Noida","Delhi","Mumbai","Pune","Delhi","Noida","Pune","Mumbai",
            "Delhi","Noida","Pune","Delhi","Mumbai","Noida","Delhi","Pune","Delhi","Mumbai","Noida"],

    "Salary":[45000,52000,np.nan,38000,70000,48000,55000,np.nan,
              41000,62000,47000,65000,53000,39000,np.nan,80000,58000,51000,43000,60000],

    "Age":[24,28,30,np.nan,40,27,26,31,29,38,25,36,np.nan,33,27,41,34,26,32,np.nan],

    "Experience":[2,5,7,3,15,4,3,np.nan,6,12,2,10,5,8,np.nan,18,9,3,7,11]
}

df = pd.DataFrame(data)

In [3]:
# Show first 10 rows.
df.head(10)

   EmpID    Name Department    City   Salary   Age  Experience
0    101     Ram         IT   Delhi  45000.0  24.0         2.0
1    102   Shyam         HR   Noida  52000.0  28.0         5.0
2    103   Mohan         IT   Delhi      NaN  30.0         7.0
3    104   Rohan      Sales  Mumbai  38000.0   NaN         3.0
4    105     Anu    Finance    Pune  70000.0  40.0        15.0
5    106    Riya         HR   Delhi  48000.0  27.0         4.0
6    107  Simran         IT   Noida  55000.0  26.0         3.0
7    108    Neha    Finance    Pune      NaN  31.0         NaN
8    109   Mohit      Sales  Mumbai  41000.0  29.0         6.0
9    110  Bhavna         IT   Delhi  62000.0  38.0        12.0

In [4]:
# Show last 7 rows.
df.tail(7)

    EmpID   Name Department    City   Salary   Age  Experience
13    114  Sneha      Sales  Mumbai  39000.0  33.0         8.0
14    115  Pooja         HR   Noida      NaN  27.0         NaN
15    116  Vikas         IT   Delhi  80000.0  41.0        18.0
16    117  Nitin    Finance    Pune  58000.0  34.0         9.0
17    118   Asha         HR   Delhi  51000.0  26.0         3.0
18    119  Rahul      Sales  Mumbai  43000.0  32.0         7.0
19    120  Priya         IT   Noida  60000.0   NaN        11.0

In [5]:
# Dataset shape.
df.shape

(20, 7)

In [7]:
# Number of rows.
df.shape[0]

20

In [8]:
#Number of columns.
df.shape[1]

7

In [9]:
#Display all column names.
df.columns

Index(['EmpID', 'Name', 'Department', 'City', 'Salary', 'Age', 'Experience'], dtype='str')

In [14]:
#Display datatypes.
df.dtypes

EmpID           int64
Name              str
Department        str
City              str
Salary        float64
Age           float64
Experience    float64
dtype: object

In [15]:
#Display statistical summary.
df.describe()

           EmpID        Salary        Age  Experience
count   20.00000     17.000000  17.000000   18.000000
mean   110.50000  53352.941176  31.000000    7.222222
std      5.91608  11494.244084   5.303301    4.570436
min    101.00000  38000.000000  24.000000    2.000000
25%    105.75000  45000.000000  27.000000    3.250000
50%    110.50000  52000.000000  30.000000    6.500000
75%    115.25000  60000.000000  34.000000    9.750000
max    120.00000  80000.000000  41.000000   18.000000

In [36]:
#Display only Name column.
df['Name']

0        Ram
1      Shyam
2      Mohan
3      Rohan
4        Anu
5       Riya
6     Simran
7       Neha
8      Mohit
9     Bhavna
10     Karan
11      Amit
12       NaN
13     Sneha
14     Pooja
15     Vikas
16     Nitin
17      Asha
18     Rahul
19     Priya
Name: Name, dtype: str

In [42]:
#Display Name and Salary.
df[['Name' ,  'Salary']]

      Name   Salary
0      Ram  45000.0
1    Shyam  52000.0
2    Mohan      NaN
3    Rohan  38000.0
4      Anu  70000.0
5     Riya  48000.0
6   Simran  55000.0
7     Neha      NaN
8    Mohit  41000.0
9   Bhavna  62000.0
10   Karan  47000.0
11    Amit  65000.0
12     NaN  53000.0
13   Sneha  39000.0
14   Pooja      NaN
15   Vikas  80000.0
16   Nitin  58000.0
17    Asha  51000.0
18   Rahul  43000.0
19   Priya  60000.0

In [43]:
#Find average salary.
df.Salary.mean()

np.float64(53352.94117647059)

In [44]:
#Find highest salary.
df.Salary.max()

np.float64(80000.0)

In [45]:
#Find lowest salary
df.Salary.min()

np.float64(38000.0)

In [46]:
#Find total salary.
df.Salary.sum()

np.float64(907000.0)

In [47]:
#Count missing values.
df.isnull().sum()

EmpID         0
Name          1
Department    0
City          0
Salary        3
Age           3
Experience    2
dtype: int64

In [48]:
#Total missing values.
df.isnull().sum().sum()

np.int64(9)

In [50]:
#Replace missing Name.
df.Name.fillna('Unknown')

0         Ram
1       Shyam
2       Mohan
3       Rohan
4         Anu
5        Riya
6      Simran
7        Neha
8       Mohit
9      Bhavna
10      Karan
11       Amit
12    Unknown
13      Sneha
14      Pooja
15      Vikas
16      Nitin
17       Asha
18      Rahul
19      Priya
Name: Name, dtype: str

In [54]:
#Fill Salary with mean.
df.Salary.fillna(round(df.Salary.mean(),2))

0     45000.00
1     52000.00
2     53352.94
3     38000.00
4     70000.00
5     48000.00
6     55000.00
7     53352.94
8     41000.00
9     62000.00
10    47000.00
11    65000.00
12    53000.00
13    39000.00
14    53352.94
15    80000.00
16    58000.00
17    51000.00
18    43000.00
19    60000.00
Name: Salary, dtype: float64

In [56]:
#Fill Age with mean.
df.Age.fillna(df.Age.mean())

0     24.0
1     28.0
2     30.0
3     31.0
4     40.0
5     27.0
6     26.0
7     31.0
8     29.0
9     38.0
10    25.0
11    36.0
12    31.0
13    33.0
14    27.0
15    41.0
16    34.0
17    26.0
18    32.0
19    31.0
Name: Age, dtype: float64

In [58]:
#Fill Experience with mean.
df.Experience.fillna(df.Experience.mean().round(2))

0      2.00
1      5.00
2      7.00
3      3.00
4     15.00
5      4.00
6      3.00
7      7.22
8      6.00
9     12.00
10     2.00
11    10.00
12     5.00
13     8.00
14     7.22
15    18.00
16     9.00
17     3.00
18     7.00
19    11.00
Name: Experience, dtype: float64

In [59]:
# 🟡 Intermediate (25 Questions)
# Rename Salary to MonthlySalary.
# Rename Department to Dept.
# Show only IT employees.
# Show HR employees.
# Employees whose salary > 50000.
# Salary between 45000 and 70000.
# Age > 30.
# Experience > 5.
# Employees from Delhi.
# Employees from Delhi and IT.
# Employees from Mumbai or Pune.
# Count unique cities.
# Display all unique departments.
# Count employees department-wise.
# Count employees city-wise.
# Most common city.
# Most common department.
# Sort salary ascending.
# Sort salary descending.
# Sort City then Salary descending.
# Drop duplicate cities.
# Use isin() to display Delhi, Noida and Pune employees.
# Display numeric columns only.
# Display string columns only.
# Convert first 3 letters of Name using lambda.

In [67]:
# Rename Salary to MonthlySalary.
df.rename(columns= {'Salary':'MonthlySalary'})

    EmpID    Name Department    City  MonthlySalary   Age  Experience
0     101     Ram         IT   Delhi        45000.0  24.0         2.0
1     102   Shyam         HR   Noida        52000.0  28.0         5.0
2     103   Mohan         IT   Delhi            NaN  30.0         7.0
3     104   Rohan      Sales  Mumbai        38000.0   NaN         3.0
4     105     Anu    Finance    Pune        70000.0  40.0        15.0
5     106    Riya         HR   Delhi        48000.0  27.0         4.0
6     107  Simran         IT   Noida        55000.0  26.0         3.0
7     108    Neha    Finance    Pune            NaN  31.0         NaN
8     109   Mohit      Sales  Mumbai        41000.0  29.0         6.0
9     110  Bhavna         IT   Delhi        62000.0  38.0        12.0
10    111   Karan         HR   Noida        47000.0  25.0         2.0
11    112    Amit    Finance    Pune        65000.0  36.0        10.0
12    113     NaN         IT   Delhi        53000.0   NaN         5.0
13    114   Sneha      Sales  Mumbai        39000.0  33.0         8.0
14    115   Pooja         HR   Noida            NaN  27.0         NaN
15    116   Vikas         IT   Delhi        80000.0  41.0        18.0
16    117   Nitin    Finance    Pune        58000.0  34.0         9.0
17    118    Asha         HR   Delhi        51000.0  26.0         3.0
18    119   Rahul      Sales  Mumbai        43000.0  32.0         7.0
19    120   Priya         IT   Noida        60000.0   NaN        11.0

In [68]:
#Rename Department to Dept.
df.rename(columns= {'Department' : 'Dept'})

    EmpID    Name     Dept    City   Salary   Age  Experience
0     101     Ram       IT   Delhi  45000.0  24.0         2.0
1     102   Shyam       HR   Noida  52000.0  28.0         5.0
2     103   Mohan       IT   Delhi      NaN  30.0         7.0
3     104   Rohan    Sales  Mumbai  38000.0   NaN         3.0
4     105     Anu  Finance    Pune  70000.0  40.0        15.0
5     106    Riya       HR   Delhi  48000.0  27.0         4.0
6     107  Simran       IT   Noida  55000.0  26.0         3.0
7     108    Neha  Finance    Pune      NaN  31.0         NaN
8     109   Mohit    Sales  Mumbai  41000.0  29.0         6.0
9     110  Bhavna       IT   Delhi  62000.0  38.0        12.0
10    111   Karan       HR   Noida  47000.0  25.0         2.0
11    112    Amit  Finance    Pune  65000.0  36.0        10.0
12    113     NaN       IT   Delhi  53000.0   NaN         5.0
13    114   Sneha    Sales  Mumbai  39000.0  33.0         8.0
14    115   Pooja       HR   Noida      NaN  27.0         NaN
15    116   Vikas       IT   Delhi  80000.0  41.0        18.0
16    117   Nitin  Finance    Pune  58000.0  34.0         9.0
17    118    Asha       HR   Delhi  51000.0  26.0         3.0
18    119   Rahul    Sales  Mumbai  43000.0  32.0         7.0
19    120   Priya       IT   Noida  60000.0   NaN        11.0

In [73]:
#Show only IT employees.
df[df['Department']=='IT']

    EmpID    Name Department   City   Salary   Age  Experience
0     101     Ram         IT  Delhi  45000.0  24.0         2.0
2     103   Mohan         IT  Delhi      NaN  30.0         7.0
6     107  Simran         IT  Noida  55000.0  26.0         3.0
9     110  Bhavna         IT  Delhi  62000.0  38.0        12.0
12    113     NaN         IT  Delhi  53000.0   NaN         5.0
15    116   Vikas         IT  Delhi  80000.0  41.0        18.0
19    120   Priya         IT  Noida  60000.0   NaN        11.0

In [75]:
#Show HR employees.
df[df.Department == 'HR']

    EmpID   Name Department   City   Salary   Age  Experience
1     102  Shyam         HR  Noida  52000.0  28.0         5.0
5     106   Riya         HR  Delhi  48000.0  27.0         4.0
10    111  Karan         HR  Noida  47000.0  25.0         2.0
14    115  Pooja         HR  Noida      NaN  27.0         NaN
17    118   Asha         HR  Delhi  51000.0  26.0         3.0

In [77]:
#Employees whose salary > 50000.
df[df.Salary>50000]

    EmpID    Name Department   City   Salary   Age  Experience
1     102   Shyam         HR  Noida  52000.0  28.0         5.0
4     105     Anu    Finance   Pune  70000.0  40.0        15.0
6     107  Simran         IT  Noida  55000.0  26.0         3.0
9     110  Bhavna         IT  Delhi  62000.0  38.0        12.0
11    112    Amit    Finance   Pune  65000.0  36.0        10.0
12    113     NaN         IT  Delhi  53000.0   NaN         5.0
15    116   Vikas         IT  Delhi  80000.0  41.0        18.0
16    117   Nitin    Finance   Pune  58000.0  34.0         9.0
17    118    Asha         HR  Delhi  51000.0  26.0         3.0
19    120   Priya         IT  Noida  60000.0   NaN        11.0

In [89]:
#Salary between 45000 and 70000.
mask1 = df.Salary>45000 
mask2 = df.Salary<70000
df[mask1 & mask2]

    EmpID    Name Department   City   Salary   Age  Experience
1     102   Shyam         HR  Noida  52000.0  28.0         5.0
5     106    Riya         HR  Delhi  48000.0  27.0         4.0
6     107  Simran         IT  Noida  55000.0  26.0         3.0
9     110  Bhavna         IT  Delhi  62000.0  38.0        12.0
10    111   Karan         HR  Noida  47000.0  25.0         2.0
11    112    Amit    Finance   Pune  65000.0  36.0        10.0
12    113     NaN         IT  Delhi  53000.0   NaN         5.0
16    117   Nitin    Finance   Pune  58000.0  34.0         9.0
17    118    Asha         HR  Delhi  51000.0  26.0         3.0
19    120   Priya         IT  Noida  60000.0   NaN        11.0

In [90]:
#Age > 30.
df[df.Age>30]

    EmpID    Name Department    City   Salary   Age  Experience
4     105     Anu    Finance    Pune  70000.0  40.0        15.0
7     108    Neha    Finance    Pune      NaN  31.0         NaN
9     110  Bhavna         IT   Delhi  62000.0  38.0        12.0
11    112    Amit    Finance    Pune  65000.0  36.0        10.0
13    114   Sneha      Sales  Mumbai  39000.0  33.0         8.0
15    116   Vikas         IT   Delhi  80000.0  41.0        18.0
16    117   Nitin    Finance    Pune  58000.0  34.0         9.0
18    119   Rahul      Sales  Mumbai  43000.0  32.0         7.0

In [91]:
#Experience > 5.
df[df.Experience > 5 ]

    EmpID    Name Department    City   Salary   Age  Experience
2     103   Mohan         IT   Delhi      NaN  30.0         7.0
4     105     Anu    Finance    Pune  70000.0  40.0        15.0
8     109   Mohit      Sales  Mumbai  41000.0  29.0         6.0
9     110  Bhavna         IT   Delhi  62000.0  38.0        12.0
11    112    Amit    Finance    Pune  65000.0  36.0        10.0
13    114   Sneha      Sales  Mumbai  39000.0  33.0         8.0
15    116   Vikas         IT   Delhi  80000.0  41.0        18.0
16    117   Nitin    Finance    Pune  58000.0  34.0         9.0
18    119   Rahul      Sales  Mumbai  43000.0  32.0         7.0
19    120   Priya         IT   Noida  60000.0   NaN        11.0

In [93]:
#Employees from Delhi
df[df['City'] == 'Delhi']

    EmpID    Name Department   City   Salary   Age  Experience
0     101     Ram         IT  Delhi  45000.0  24.0         2.0
2     103   Mohan         IT  Delhi      NaN  30.0         7.0
5     106    Riya         HR  Delhi  48000.0  27.0         4.0
9     110  Bhavna         IT  Delhi  62000.0  38.0        12.0
12    113     NaN         IT  Delhi  53000.0   NaN         5.0
15    116   Vikas         IT  Delhi  80000.0  41.0        18.0
17    118    Asha         HR  Delhi  51000.0  26.0         3.0

In [94]:
#Employees from Delhi and IT.
mask1 = df.City == 'Delhi'
mask2 = df.Department=='IT'
df[mask1 & mask2]

    EmpID    Name Department   City   Salary   Age  Experience
0     101     Ram         IT  Delhi  45000.0  24.0         2.0
2     103   Mohan         IT  Delhi      NaN  30.0         7.0
9     110  Bhavna         IT  Delhi  62000.0  38.0        12.0
12    113     NaN         IT  Delhi  53000.0   NaN         5.0
15    116   Vikas         IT  Delhi  80000.0  41.0        18.0