In [129]:
#Create DataFrame.
import pandas as pd
import numpy as np

employee = {
'EmpID':[101,102,103,104,105,106,107,108,109,110,111,112],
'Name':['Ram','Shyam',np.nan,'Rohan','Anu','Riya','Simran',
'Neha','Mohit','Bhavna','Amit',np.nan],

'Department':['IT','HR','IT','Finance','Sales',
'HR','IT','Finance','Sales','IT','HR','IT'],

'Salary':[45000,52000,np.nan,65000,
38000,47000,np.nan,72000,41000,58000,49000,np.nan],

'Age':[24,28,np.nan,35,29,
31,27,np.nan,30,36,26,np.nan],

'Experience':[2,5,7,np.nan,
4,6,3,12,np.nan,9,2,5]
}

df = pd.DataFrame(employee)

In [10]:
# 2 . Check dataset information.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       12 non-null     int64
 1   Name        10 non-null     str
 2   Department  12 non-null     str
 3   Salary      9 non-null      float64
 4   Age         9 non-null      float64
 5   Experience  10 non-null     float64
dtypes: float64(3), int64(1), str(2)
memory usage: 708.0 bytes

In [19]:
#Check null values.
df.isnull()

    EmpID   Name  Department  Salary    Age  Experience
0   False  False       False   False  False       False
1   False  False       False   False  False       False
2   False   True       False    True   True       False
3   False  False       False   False  False        True
4   False  False       False   False  False       False
5   False  False       False   False  False       False
6   False  False       False    True  False       False
7   False  False       False   False   True       False
8   False  False       False   False  False        True
9   False  False       False   False  False       False
10  False  False       False   False  False       False
11  False   True       False    True   True       False

In [35]:
#Count null values
df.isnull().sum()
df.isnull().sum()

EmpID         0
Name          0
Department    0
Salary        3
Age           3
Experience    2
dtype: int64

In [28]:
#Create copy.
newdf = df

In [30]:
#Fill Name using "Unknown".
newdf.Name = newdf.Name.fillna('Unknown')

In [31]:
newdf

    EmpID     Name Department   Salary   Age  Experience
0     101      Ram         IT  45000.0  24.0         2.0
1     102    Shyam         HR  52000.0  28.0         5.0
2     103  Unknown         IT      NaN   NaN         7.0
3     104    Rohan    Finance  65000.0  35.0         NaN
4     105      Anu      Sales  38000.0  29.0         4.0
5     106     Riya         HR  47000.0  31.0         6.0
6     107   Simran         IT      NaN  27.0         3.0
7     108     Neha    Finance  72000.0   NaN        12.0
8     109    Mohit      Sales  41000.0  30.0         NaN
9     110   Bhavna         IT  58000.0  36.0         9.0
10    111     Amit         HR  49000.0  26.0         2.0
11    112  Unknown         IT      NaN   NaN         5.0

In [36]:
#Fill Salary using mean.
newdf.Salary = newdf.Salary.fillna(df.Salary.mean())

In [40]:
#Fill Age using mean.
df.Age = df.Age.fillna(round(df.Age.mean(),2))

In [42]:
df.isnull().sum()

EmpID         0
Name          0
Department    0
Salary        0
Age           0
Experience    2
dtype: int64

In [47]:
#Fill Experience using mean.
df.Experience = df.Experience.fillna(df.Experience.mean())

In [49]:
#Verify no null values remain.
df.isnull().sum()

EmpID         0
Name          0
Department    0
Salary        0
Age           0
Experience    0
dtype: int64

In [65]:
#Total employees
newdf.shape[0]

12

In [80]:
#Average salary
newdf.Salary.mean()

np.float64(51888.88888888888)

In [82]:
#Highest salary
newdf.Salary.max()

np.float64(72000.0)

In [83]:
#Lowest salary
df['Salary'].min()

np.float64(38000.0)

In [85]:
#Average age
newdf.Age.mean()

np.float64(29.55666666666667)

In [86]:
#Average experience
newdf.Experience.mean()

np.float64(5.5)

In [87]:
#Total salary
newdf.Salary.sum()

np.float64(622666.6666666666)

In [217]:
#Employees earning more than average salary
df[df.Salary>df.Salary.mean()]

   EmpID    Name Department   Salary   Age  Experience
1    102   Shyam         HR  52000.0  28.0         5.0
3    104   Rohan    Finance  65000.0  35.0         NaN
7    108    Neha    Finance  72000.0   NaN        12.0
9    110  Bhavna         IT  58000.0  36.0         9.0

In [97]:
#Employees in IT department
df[df.Department=='IT']

    EmpID    Name Department   Salary   Age  Experience
0     101     Ram         IT  45000.0  24.0         2.0
2     103     NaN         IT      NaN   NaN         7.0
6     107  Simran         IT      NaN  27.0         3.0
9     110  Bhavna         IT  58000.0  36.0         9.0
11    112     NaN         IT      NaN   NaN         5.0

In [99]:
#Employees in HR department
df[df.Department == 'HR']

    EmpID   Name Department   Salary   Age  Experience
1     102  Shyam         HR  52000.0  28.0         5.0
5     106   Riya         HR  47000.0  31.0         6.0
10    111   Amit         HR  49000.0  26.0         2.0

In [100]:
#Employees aged above 30
df[df.Age>30]

   EmpID    Name Department   Salary   Age  Experience
3    104   Rohan    Finance  65000.0  35.0         NaN
5    106    Riya         HR  47000.0  31.0         6.0
9    110  Bhavna         IT  58000.0  36.0         9.0

In [101]:
#Employees having experience greater than 5 years
df[df["Experience"]>5]

   EmpID    Name Department   Salary   Age  Experience
2    103     NaN         IT      NaN   NaN         7.0
5    106    Riya         HR  47000.0  31.0         6.0
7    108    Neha    Finance  72000.0   NaN        12.0
9    110  Bhavna         IT  58000.0  36.0         9.0

In [226]:
#Top 3 highest paid employees
newdf.sort_values(by = 'Salary' ,  ascending = False ).head(3)

   EmpID    Name Department   Salary    Age  Experience
7    108    Neha    Finance  72000.0  29.56        12.0
3    104   Rohan    Finance  65000.0  35.00         5.5
9    110  Bhavna         IT  58000.0  36.00         9.0

In [227]:
#Top 3 lowest paid employees
newdf.sort_values(by = 'Salary' ).head(3)

   EmpID   Name Department   Salary   Age  Experience
4    105    Anu      Sales  38000.0  29.0         4.0
8    109  Mohit      Sales  41000.0  30.0         5.5
0    101    Ram         IT  45000.0  24.0         2.0

In [111]:
#Show final cleaned dataframe
newdf

    EmpID     Name Department        Salary    Age  Experience
0     101      Ram         IT  45000.000000  24.00         2.0
1     102    Shyam         HR  52000.000000  28.00         5.0
2     103  Unknown         IT  51888.888889  29.56         7.0
3     104    Rohan    Finance  65000.000000  35.00         5.5
4     105      Anu      Sales  38000.000000  29.00         4.0
5     106     Riya         HR  47000.000000  31.00         6.0
6     107   Simran         IT  51888.888889  27.00         3.0
7     108     Neha    Finance  72000.000000  29.56        12.0
8     109    Mohit      Sales  41000.000000  30.00         5.5
9     110   Bhavna         IT  58000.000000  36.00         9.0
10    111     Amit         HR  49000.000000  26.00         2.0
11    112  Unknown         IT  51888.888889  29.56         5.0

In [122]:
#Count employees department-wise.
newdf.Department.value_counts()

Department
IT         5
HR         3
Finance    2
Sales      2
Name: count, dtype: int64

In [190]:
#Find average salary department-wise.
newdf.groupby('Department')['Salary'].mean()

Department
Finance    68500.000000
HR         49333.333333
IT         51733.333333
Sales      39500.000000
Name: Salary, dtype: float64

In [192]:
#Sort employees by salary (highest to lowest).
newdf.sort_values(by='Salary', ascending=False)

    EmpID     Name Department        Salary    Age  Experience
7     108     Neha    Finance  72000.000000  29.56        12.0
3     104    Rohan    Finance  65000.000000  35.00         5.5
9     110   Bhavna         IT  58000.000000  36.00         9.0
1     102    Shyam         HR  52000.000000  28.00         5.0
11    112  Unknown         IT  51888.888889  29.56         5.0
2     103  Unknown         IT  51888.888889  29.56         7.0
6     107   Simran         IT  51888.888889  27.00         3.0
10    111     Amit         HR  49000.000000  26.00         2.0
5     106     Riya         HR  47000.000000  31.00         6.0
0     101      Ram         IT  45000.000000  24.00         2.0
8     109    Mohit      Sales  41000.000000  30.00         5.5
4     105      Anu      Sales  38000.000000  29.00         4.0

In [193]:
newdf

    EmpID     Name Department        Salary    Age  Experience
0     101      Ram         IT  45000.000000  24.00         2.0
1     102    Shyam         HR  52000.000000  28.00         5.0
2     103  Unknown         IT  51888.888889  29.56         7.0
3     104    Rohan    Finance  65000.000000  35.00         5.5
4     105      Anu      Sales  38000.000000  29.00         4.0
5     106     Riya         HR  47000.000000  31.00         6.0
6     107   Simran         IT  51888.888889  27.00         3.0
7     108     Neha    Finance  72000.000000  29.56        12.0
8     109    Mohit      Sales  41000.000000  30.00         5.5
9     110   Bhavna         IT  58000.000000  36.00         9.0
10    111     Amit         HR  49000.000000  26.00         2.0
11    112  Unknown         IT  51888.888889  29.56         5.0

In [194]:
#Sort employees by age.
newdf.sort_values(by = 'Age')

    EmpID     Name Department        Salary    Age  Experience
0     101      Ram         IT  45000.000000  24.00         2.0
10    111     Amit         HR  49000.000000  26.00         2.0
6     107   Simran         IT  51888.888889  27.00         3.0
1     102    Shyam         HR  52000.000000  28.00         5.0
4     105      Anu      Sales  38000.000000  29.00         4.0
7     108     Neha    Finance  72000.000000  29.56        12.0
11    112  Unknown         IT  51888.888889  29.56         5.0
2     103  Unknown         IT  51888.888889  29.56         7.0
8     109    Mohit      Sales  41000.000000  30.00         5.5
5     106     Riya         HR  47000.000000  31.00         6.0
3     104    Rohan    Finance  65000.000000  35.00         5.5
9     110   Bhavna         IT  58000.000000  36.00         9.0

In [229]:
#Rename Column
newdf.rename(columns = {'Umar' : 'Age' , 'Salary' : 'Income'})

    EmpID     Name Department        Income    Age  Experience
0     101      Ram         IT  45000.000000  24.00         2.0
1     102    Shyam         HR  52000.000000  28.00         5.0
2     103  Unknown         IT  51888.888889  29.56         7.0
3     104    Rohan    Finance  65000.000000  35.00         5.5
4     105      Anu      Sales  38000.000000  29.00         4.0
5     106     Riya         HR  47000.000000  31.00         6.0
6     107   Simran         IT  51888.888889  27.00         3.0
7     108     Neha    Finance  72000.000000  29.56        12.0
8     109    Mohit      Sales  41000.000000  30.00         5.5
9     110   Bhavna         IT  58000.000000  36.00         9.0
10    111     Amit         HR  49000.000000  26.00         2.0
11    112  Unknown         IT  51888.888889  29.56         5.0

In [219]:
#saved file to csv
newdf.to_csv('Cleaned Dataframe.csv' , index = False)

In [ ]:
newdf

In [220]:
#read File
newh = pd.read_csv(r"E:\Croma\Python\Jupyter Notebook LocalComputer\Cleaned Dataframe.csv")

In [214]:
newh

    EmpID     Name Department        Salary    Age  Experience
0     101      Ram         IT  45000.000000  24.00         2.0
1     102    Shyam         HR  52000.000000  28.00         5.0
2     103  Unknown         IT  51888.888889  29.56         7.0
3     104    Rohan    Finance  65000.000000  35.00         5.5
4     105      Anu      Sales  38000.000000  29.00         4.0
5     106     Riya         HR  47000.000000  31.00         6.0
6     107   Simran         IT  51888.888889  27.00         3.0
7     108     Neha    Finance  72000.000000  29.56        12.0
8     109    Mohit      Sales  41000.000000  30.00         5.5
9     110   Bhavna         IT  58000.000000  36.00         9.0
10    111     Amit         HR  49000.000000  26.00         2.0
11    112  Unknown         IT  51888.888889  29.56         5.0

In [221]:
#Export To Excel
newh.to_excel('hello.xlsx' , index = False)

In [234]:
df[df.Department.isin(["IT","HR"])]

    EmpID    Name Department   Salary   Age  Experience
0     101     Ram         IT  45000.0  24.0         2.0
1     102   Shyam         HR  52000.0  28.0         5.0
2     103     NaN         IT      NaN   NaN         7.0
5     106    Riya         HR  47000.0  31.0         6.0
6     107  Simran         IT      NaN  27.0         3.0
9     110  Bhavna         IT  58000.0  36.0         9.0
10    111    Amit         HR  49000.0  26.0         2.0
11    112     NaN         IT      NaN   NaN         5.0