In [172]:
import pandas as pd
import numpy as np

data = {
    "EmpID":[101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
    "Name":["Ram","Shyam","Mohan","Rohan","Anu","Riya","Simran","Neha",
            "Mohit","Bhavna","Karan","Amit",np.nan,"Sneha","Pooja"],
    "Department":["IT","HR","IT","Sales","Finance","HR","IT",
                  "Finance","Sales","IT","HR","Finance",
                  "IT","Sales","HR"],
    "Salary":[45000,52000,np.nan,38000,70000,48000,55000,
              np.nan,41000,62000,47000,65000,53000,39000,np.nan],
    "Age":[24,28,30,np.nan,40,27,26,31,29,38,25,36,np.nan,33,27],
    "Experience":[2,5,7,3,15,4,3,np.nan,6,12,2,10,5,8,np.nan]
}

df = pd.DataFrame(data)

In [5]:
# Q1) Display first 5 rows.
df.head()

   EmpID   Name Department   Salary   Age  Experience
0    101    Ram         IT  45000.0  24.0         2.0
1    102  Shyam         HR  52000.0  28.0         5.0
2    103  Mohan         IT      NaN  30.0         7.0
3    104  Rohan      Sales  38000.0   NaN         3.0
4    105    Anu    Finance  70000.0  40.0        15.0

In [6]:
# Q2) Display first 8 rows.
df.head(8)

   EmpID    Name Department   Salary   Age  Experience
0    101     Ram         IT  45000.0  24.0         2.0
1    102   Shyam         HR  52000.0  28.0         5.0
2    103   Mohan         IT      NaN  30.0         7.0
3    104   Rohan      Sales  38000.0   NaN         3.0
4    105     Anu    Finance  70000.0  40.0        15.0
5    106    Riya         HR  48000.0  27.0         4.0
6    107  Simran         IT  55000.0  26.0         3.0
7    108    Neha    Finance      NaN  31.0         NaN

In [8]:
# Q3) Display last 4 rows.
df.tail(4)

    EmpID   Name Department   Salary   Age  Experience
11    112   Amit    Finance  65000.0  36.0        10.0
12    113    NaN         IT  53000.0   NaN         5.0
13    114  Sneha      Sales  39000.0  33.0         8.0
14    115  Pooja         HR      NaN  27.0         NaN

In [10]:
#Q4 Show complete information of dataset.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       15 non-null     int64
 1   Name        14 non-null     str
 2   Department  15 non-null     str
 3   Salary      12 non-null     float64
 4   Age         13 non-null     float64
 5   Experience  13 non-null     float64
dtypes: float64(3), int64(1), str(2)
memory usage: 852.0 bytes

In [11]:
#Q5. Show statistical summary.
df.describe()

            EmpID        Salary        Age  Experience
count   15.000000     12.000000  13.000000   13.000000
mean   108.000000  51250.000000  30.307692    6.307692
std      4.472136  10323.186612   5.072551    4.008005
min    101.000000  38000.000000  24.000000    2.000000
25%    104.500000  44000.000000  27.000000    3.000000
50%    108.000000  50000.000000  29.000000    5.000000
75%    111.500000  56750.000000  33.000000    8.000000
max    115.000000  70000.000000  40.000000   15.000000

In [16]:
#Q6 Display only Name column.
df['Name']

0        Ram
1      Shyam
2      Mohan
3      Rohan
4        Anu
5       Riya
6     Simran
7       Neha
8      Mohit
9     Bhavna
10     Karan
11      Amit
12       NaN
13     Sneha
14     Pooja
Name: Name, dtype: str

In [17]:
#Q7 Display Salary column.
df.Salary

0     45000.0
1     52000.0
2         NaN
3     38000.0
4     70000.0
5     48000.0
6     55000.0
7         NaN
8     41000.0
9     62000.0
10    47000.0
11    65000.0
12    53000.0
13    39000.0
14        NaN
Name: Salary, dtype: float64

In [18]:
#Q8 Find total salary.
df.Salary.sum()

np.float64(615000.0)

In [19]:
#Q9Find average salary.
df.Salary.mean()

np.float64(51250.0)

In [20]:
#Q10 Find maximum salary.
df.Salary.max()

np.float64(70000.0)

In [21]:
#Q11 Find manimum salary.
df.Salary.min()

np.float64(38000.0)

In [28]:
#Q12 Find total employees.
len(df)

15

In [39]:
df.shape[0]

15

In [40]:
df.EmpID.count()

np.int64(15)

In [42]:
#Q13 Count missing values in each column.
df.isnull().sum()

EmpID         0
Name          1
Department    0
Salary        3
Age           2
Experience    2
dtype: int64

In [44]:
#Q14 Find total missing values in dataset.
df.isnull().sum().sum()

np.int64(8)

In [52]:
#Q15 Display rows having missing values.
df[df.isnull().any(axis=1)]

    EmpID   Name Department   Salary   Age  Experience
2     103  Mohan         IT      NaN  30.0         7.0
3     104  Rohan      Sales  38000.0   NaN         3.0
7     108   Neha    Finance      NaN  31.0         NaN
12    113    NaN         IT  53000.0   NaN         5.0
14    115  Pooja         HR      NaN  27.0         NaN

In [61]:
#Q16Create a copy of dataframe.
newdf = df.copy()

In [63]:
#Q17Fill missing Salary using average salary.

newdf.Salary = newdf.Salary.fillna(newdf.Salary.mean())

In [69]:
#Q18 Fill missing Age using average age.
newdf.Age = newdf.Age.fillna(round(newdf.Age.mean(),2))

In [138]:
#Q19 Fill missing Experience using average experience.
newdf.Experience = newdf.Experience.fillna(round(newdf.Experience.mean(),2))
# round(value like 2 and others) ==> it is used to round the values after point values 2.98232783==>2.98
newdf.Experience =  newdf.Experience.round(2)

In [139]:
newdf.Experience

0      2.00
1      5.00
2      7.00
3      3.00
4     15.00
5      4.00
6      3.00
7      6.31
8      6.00
9     12.00
10     2.00
11    10.00
12     5.00
13     8.00
14     6.31
Name: Experience, dtype: float64

In [87]:
#Q20Replace missing Name with "Unknown".
newdf.Name = newdf.Name.fillna('Unknown')

In [211]:
#Q21 Check whether any null value still exists.
newdf.isnull().sum()

EmpID         0
Name          0
Department    0
Salary        0
Age           0
Experience    0
dtype: int64

In [95]:
#Q22Remove rows having null values.
df = df.dropna()

In [96]:
#Q23 Show first 3 rows after removing null values.
df.head(3)

   EmpID   Name Department   Salary   Age  Experience
0    101    Ram         IT  45000.0  24.0         2.0
1    102  Shyam         HR  52000.0  28.0         5.0
4    105    Anu    Finance  70000.0  40.0        15.0

In [97]:
#Q24 Find total salary after filling null values.
newdf.Salary.sum()

np.float64(768750.0)

In [101]:
#Q25 Find highest salary.
newdf.Salary.max()

np.float64(70000.0)

In [113]:
#Q26 Find lowest salary.
df.Salary.min()

np.float64(39000.0)

In [114]:
#Q27 Find average experience.
df.Experience.mean()

np.float64(6.7)

In [118]:
#Q28 Find average age.
df.Age.mean()
newdf.Age.mean().round(2)

np.float64(30.31)

In [124]:
#Q29 Display only Name and Salary columns.
df[['Name','Salary' ]]

      Name   Salary   Age
0      Ram  45000.0  24.0
1    Shyam  52000.0  28.0
4      Anu  70000.0  40.0
5     Riya  48000.0  27.0
6   Simran  55000.0  26.0
8    Mohit  41000.0  29.0
9   Bhavna  62000.0  38.0
10   Karan  47000.0  25.0
11    Amit  65000.0  36.0
13   Sneha  39000.0  33.0

In [125]:
#Q30 Display Name, Department and Salary. 
df[['Name', 'Department', 'Salary']]

      Name Department   Salary
0      Ram         IT  45000.0
1    Shyam         HR  52000.0
4      Anu    Finance  70000.0
5     Riya         HR  48000.0
6   Simran         IT  55000.0
8    Mohit      Sales  41000.0
9   Bhavna         IT  62000.0
10   Karan         HR  47000.0
11    Amit    Finance  65000.0
13   Sneha      Sales  39000.0

In [126]:
#Q31 Find maximum age.
df.Age.max()

np.float64(40.0)

In [127]:
#Q32 Find minimum age.
df.Age.min()

np.float64(24.0)

In [128]:
#Q33 Find total experience.
df.Experience.sum()

np.float64(67.0)

In [131]:
#Q34 Find average of Salary rounded to 2 decimals.
df.Salary.mean().round(2)

np.float64(52400.0)

In [135]:
#Q35 Check datatype of every column.
df.dtypes

EmpID           int64
Name              str
Department        str
Salary        float64
Age           float64
Experience    float64
dtype: object

In [144]:
#Q36 Find employees whose salary is greater than average salary.
df.Name[df.Salary>df.Salary.mean()]

4        Anu
6     Simran
9     Bhavna
11      Amit
Name: Name, dtype: str

In [149]:
#Q37 Find employees whose age is greater than 30.
df.Name[df.Age>30]

4        Anu
9     Bhavna
11      Amit
13     Sneha
Name: Name, dtype: str

In [163]:
#Q38Find employees having salary greater than 50000.
df['Name'][df.Salary>50000]

1      Shyam
4        Anu
6     Simran
9     Bhavna
11      Amit
Name: Name, dtype: str

In [168]:
#Q39 Find employees whose department is IT.
df.Name[df.Department=='IT']

0       Ram
6    Simran
9    Bhavna
Name: Name, dtype: str

In [170]:
#Q40 Find employees whose department is HR.
df.Name[df.Department=='HR']

1     Shyam
5      Riya
10    Karan
Name: Name, dtype: str

In [175]:
#Q41 Find employees having missing salary.
df.Name[df.Salary.isnull()]

2     Mohan
7      Neha
14    Pooja
Name: Name, dtype: str

In [177]:
#Q42 Find employees having missing name.
df[df.Name.isnull()]

    EmpID Name Department   Salary  Age  Experience
12    113  NaN         IT  53000.0  NaN         5.0

In [179]:
#Q43  Display only employees whose experience is greater than 5.
df.Name[df.Experience>5]

2      Mohan
4        Anu
8      Mohit
9     Bhavna
11      Amit
13     Sneha
Name: Name, dtype: str

In [182]:
#Q44 Display employees whose salary is between 40000 and 60000.
df.Name[(df.Salary<60000) & (df.Salary>40000)]

0        Ram
1      Shyam
5       Riya
6     Simran
8      Mohit
10     Karan
12       NaN
Name: Name, dtype: str

In [213]:
#Q45 Display employees whose age is less than average age.
df[df.Age<df.Age.mean()]

    EmpID    Name Department   Salary   Age  Experience
0     101     Ram         IT  45000.0  24.0         2.0
1     102   Shyam         HR  52000.0  28.0         5.0
2     103   Mohan         IT      NaN  30.0         7.0
5     106    Riya         HR  48000.0  27.0         4.0
6     107  Simran         IT  55000.0  26.0         3.0
8     109   Mohit      Sales  41000.0  29.0         6.0
10    111   Karan         HR  47000.0  25.0         2.0
14    115   Pooja         HR      NaN  27.0         NaN

In [194]:
#Q46 Find employee having maximum salary.
df[df.Salary==df.Salary.max()]

   EmpID Name Department   Salary   Age  Experience
4    105  Anu    Finance  70000.0  40.0        15.0

In [197]:
#Q47 Find employee having minimum salary.
df[df.Salary==df.Salary.min()]

   EmpID   Name Department   Salary  Age  Experience
3    104  Rohan      Sales  38000.0  NaN         3.0

In [210]:
#Q48 Display top 5 highest salary employees.
df.nlargest(5,'Salary')
df.sort_values(by="Salary", ascending=False).head(5)

    EmpID    Name Department   Salary   Age  Experience
4     105     Anu    Finance  70000.0  40.0        15.0
11    112    Amit    Finance  65000.0  36.0        10.0
9     110  Bhavna         IT  62000.0  38.0        12.0
6     107  Simran         IT  55000.0  26.0         3.0
12    113     NaN         IT  53000.0   NaN         5.0

In [207]:
#Q49 Display top 5 lowest salary employees.
df.nsmallest(5,'Salary')
df.sort_values(by="Salary" , ascending=True).head(5)

    EmpID   Name Department   Salary   Age  Experience
3     104  Rohan      Sales  38000.0   NaN         3.0
13    114  Sneha      Sales  39000.0  33.0         8.0
8     109  Mohit      Sales  41000.0  29.0         6.0
0     101    Ram         IT  45000.0  24.0         2.0
10    111  Karan         HR  47000.0  25.0         2.0

In [209]:
#Q50Display dataframe after replacing every missing value correctly.
newdf.isnull().sum().sum()

np.int64(0)